/*
 * Copyright (c) 2020. Olá todos os direitos reservados para IT CODE TECHS SYSTEMS.
 * Local do Arquivo: (/Users/andersons.andrade/Desktop/JAVA/SPRING/DEVELOPER/vendas/src/main/resources/meuschema.sql)
 * Projeto: vendas -> vendas -> meuschema.sql
 * Criador: andersons.andrade
 * Última Modificação: 24/11/2020 18:57
 */

CREATE TABLE CLIENTE(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC (20,2)
);

CREATE TABLE PEDIDO(
    ID INTEGER PRIMARY  KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER  REFERENCES  CLIENTE (ID),
    DATA_PEDIDO TIMESTAMP ,
    TOTAL NUMERIC (20,2)
);

CREATE TABLE ITEM_PEDIDO(
    ID INTEGER PRIMARY  KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER  REFERENCES  PEDIDO (ID),
    PRODUTO_ID INTEGER  REFERENCES  PRODUTO (ID),
    QUANTIDADE INTEGER
);